### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by may-phyu** [Topaz1618/CycleganSA#1]
Currently, I am facing this error when I run train.py with my custom dataset. Please help me how to fix it I do appreciate and do thank you so much for your kindness.
Traceback (most recent call last):
  File "train.py", line 46, in <module>
    model = create_model(opt)      # create a model given opt.model and other options
  File "/home/prip/CycleganSA/models/__init__.py", line 65, in create_model
    instance = model(opt)
  File "/home/prip/CycleganSA/models/cycle_gan_model.py", line 53, in __init__
    BaseModel.__init__(self, opt)
  File "/home/prip/CycleganSA/models/base_model.py", line 35, in __init__
    self.device = torch.device('cuda:{}'.format(self.gpu_ids[0])) if self.gpu_ids else torch.device('cpu')  # get device name: CPU or GPU

**Comment by Topaz1618** [comment]
Hi may-phyu, sorry for the late response, I've just fixed it.

**Comment by may-phyu** [comment]
Hi 
Now it is successfully training and I would like to know that this is training for cyclegan "python train.py --dataroot ./datasets/horse2zebra --name horse2zebra --model cycle_gan", right? If I wanna train self-attention Cyclegan "sagan_deep.py and sagan_shallow.py" how I should train it, please help me again. I do appreciate your generous kindness and sharing your source code. It helps me a lot.

**Comment by may-phyu** [comment]
Hi 
I am sorry to bother you like this I am still facing this error when I define gpu_ids 0 or 1, please help me.
Traceback (most recent call last):
  File "train.py", line 46, in <module>
    model = create_model(opt)      # create a model given opt.model and other options
  File "/home/prip/CycleganSA/models/__init__.py", line 65, in create_model
    instance = model(opt)
  File "/home/prip/CycleganSA/models/cycle_gan_model.py", line 74, in __init__
    not opt.no_dropout, opt.init_type, opt.init_gain, self.gpu_ids)
  File "/home/prip/CycleganSA/models/networks.py", line 162, in define_G
    return init_net(net, init_type, init_gain, gpu_ids)
  File "/home/prip/CycleganSA/models/networks.py", line 112, in init_net
    if len(gpu_ids) > 0:
TypeError: object of type 'int' has no len()

**Comment by YuriyEmpty** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @renlifu, @DurianLian, @myafer, @luosong33, @madawei2699, @LiZhYun, @bladereo
